# Generated by Django 5.0.6 on 2024-07-18 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('workers', '0003_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapravka_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва компанії')),
                ('status', models.CharField(choices=[('Заправлений', 'Заправлений'), ('Порожній', 'Порожній')], default='Заправлений', max_length=50, verbose_name='Статус')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Компанія')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.department', verbose_name='Підрозділ')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Працівник')),
            ],
        ),
    ]
