# Generated by Django 5.0.6 on 2024-07-12 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipmentinventory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttransfer',
            name='from_company',
        ),
        migrations.RemoveField(
            model_name='equipmenttransfer',
            name='from_department',
        ),
        migrations.RemoveField(
            model_name='equipmenttransfer',
            name='from_employee',
        ),
        migrations.RemoveField(
            model_name='equipmenttransfer',
            name='item',
        ),
        migrations.AddField(
            model_name='equipmenttransfer',
            name='receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentreceipt', verbose_name='Прихід'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentreceipt',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Працівник'),
        ),
        migrations.AlterField(
            model_name='equipmenttransfer',
            name='to_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to=settings.AUTH_USER_MODEL, verbose_name='До працівника'),
        ),
    ]
