# Generated by Django 5.0.6 on 2024-07-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_equipmenttransfer_from_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinventory',
            options={'verbose_name': 'Запас обладнання', 'verbose_name_plural': 'Запаси обладнання'},
        ),
    ]
