# Generated by Django 5.0.6 on 2024-07-12 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('equipment', '0004_alter_equipmentinventory_options'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentreceipt',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Працівник'),
        ),
        migrations.AlterField(
            model_name='equipmenttransfer',
            name='to_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='До компанії'),
        ),
        migrations.AlterField(
            model_name='equipmenttransfer',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.department', verbose_name='До підрозділу'),
        ),
        migrations.AlterField(
            model_name='equipmenttransfer',
            name='to_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='До працівника'),
        ),
        migrations.AlterField(
            model_name='equipmentwriteoff',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Працівник'),
        ),
    ]
