# Generated by Django 5.0.6 on 2024-07-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipmentreceipt_employee_and_more'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinventory',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='equipmentinventory',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Працівник'),
        ),
        migrations.AlterField(
            model_name='equipmentinventory',
            name='status',
            field=models.CharField(choices=[('in_use', 'Використовується'), ('in_storage', 'На складі'), ('under_maintenance', 'На обслуговуванні')], max_length=255),
        ),
    ]
