# Generated by Django 5.0.6 on 2024-07-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipmentinventory_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentinventory',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='equipmentinventory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='equipmentreceipt',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='equipmentinventory',
            name='quantity',
            field=models.IntegerField(verbose_name='Кількість'),
        ),
    ]
