# Generated by Django 5.0.6 on 2024-07-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_remove_equipmentinventory_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentinventory',
            name='quantity',
        ),
    ]
