# Generated by Django 5.0.6 on 2024-07-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('equipment', '0008_remove_equipmentinventory_quantity'),
        ('nomenklatyra', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentreceipt',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='equipmentreceipt',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipmentreceipt',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.department'),
        ),
        migrations.AlterField(
            model_name='equipmentreceipt',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker'),
        ),
        migrations.AlterField(
            model_name='equipmentreceipt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenklatyra.product'),
        ),
    ]
