# Generated by Django 5.0.6 on 2024-07-15 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_equipmentreceipt_company_and_more'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinventory',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Працівник'),
        ),
    ]
