# Generated by Django 5.0.6 on 2024-07-15 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_remove_equipmentinventory_item_and_more'),
        ('nomenklatyra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentinventory',
            name='receipt',
        ),
        migrations.AddField(
            model_name='equipmentinventory',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nomenklatyra.product', verbose_name='Номенклатура'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentinventory',
            name='status',
            field=models.CharField(default='in_storage', max_length=50, verbose_name='Статус'),
        ),
    ]
