# Generated by Django 5.0.6 on 2024-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_remove_equipmentinventory_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinventory',
            name='status',
            field=models.CharField(default='Прихід товару', max_length=50, verbose_name='Статус'),
        ),
    ]
