# Generated by Django 5.0.6 on 2024-07-18 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_alter_equipmentinventory_status'),
        ('tasks', '0004_task_task_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentreceipt',
            name='task',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'В процесі'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task', verbose_name='На основі задачі'),
        ),
    ]
