# Generated by Django 5.0.6 on 2024-07-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_alter_equipmentinventory_status'),
        ('tasks', '0002_remove_task_deadline_remove_task_title_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentinventory', verbose_name='Обладнання'),
        ),
    ]
