# Generated by Django 5.0.6 on 2024-07-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Номер завдання'),
            preserve_default=False,
        ),
    ]
