# Generated by Django 5.0.6 on 2024-07-12 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('gw', models.GenericIPAddressField(blank=True, null=True, verbose_name='GW')),
                ('mask', models.GenericIPAddressField(blank=True, null=True, verbose_name='Mask')),
                ('dns', models.GenericIPAddressField(blank=True, null=True, verbose_name='DNS')),
                ('login', models.CharField(blank=True, max_length=255, null=True, verbose_name='Login')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Password')),
                ('ipsec', models.CharField(blank=True, max_length=255, null=True, verbose_name='IPsec')),
                ('site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Додатково')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Доступ',
                'verbose_name_plural': 'Доступи',
            },
        ),
    ]
