# Generated by Django 5.0.6 on 2024-07-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Логін'),
        ),
        migrations.AlterField(
            model_name='access',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль'),
        ),
    ]
