# Generated by Django 5.0.6 on 2024-09-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_access_login_alter_access_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='access',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password'),
        ),
    ]
