# Generated by Django 5.0.6 on 2024-07-15 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Компанія'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.department', verbose_name='Підрозділ'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='hire_date',
            field=models.DateField(verbose_name='Дата прийому на роботу'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Позиція'),
        ),
    ]
