# Generated by Django 5.0.6 on 2024-07-16 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenklatyra', '0001_initial'),
        ('workers', '0002_worker_company_worker_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва обладнання')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenklatyra.product', verbose_name='Продукт')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='workers.worker', verbose_name='Працівник')),
            ],
        ),
    ]
