# Generated by Django 5.0.6 on 2024-07-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
